# Generated by Django 6.0.5 on 2026-05-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_story_conversationsession_dialogueturn_childlibrary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysession',
            name='stories_names',
            field=models.TextField(default=''),
        ),
    ]
