# Generated by Django 6.0.5 on 2026-05-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activitysession_stories_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='pin_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
