# Generated by Django 6.0.5 on 2026-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_child_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('boy', 'Garçon'), ('girl', 'Fille')], default='boy', max_length=10),
        ),
    ]
